cc_binary(
    name = 'file_watcher_test',
    srcs = [
        'file_watcher_test.cpp',
    ],
    deps = [
        '//cpp_platform/watcher:file_watcher_module'
    ]
)

cc_binary(
    name = 'filesystem_test',
    srcs = [
        'filesystem_test.cpp',
    ],
    deps = [
        '//cpp_platform/watcher:file_watcher_module'
    ]
)