/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.errorcode.manager.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 语言类型
 */
public enum Lang implements org.apache.thrift.TEnum {
  ZH(0),
  EN(1);

  private final int value;

  private Lang(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Lang findByValue(int value) { 
    switch (value) {
      case 0:
        return ZH;
      case 1:
        return EN;
      default:
        return null;
    }
  }
}
