/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.machine;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum KeyType implements org.apache.thrift.TEnum {
  KEY_HOSTNAME(1),
  KEY_HOSTINNER_IP(2);

  private final int value;

  private KeyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static KeyType findByValue(int value) { 
    switch (value) {
      case 1:
        return KEY_HOSTNAME;
      case 2:
        return KEY_HOSTINNER_IP;
      default:
        return null;
    }
  }
}
