/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.dal_set.dao;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServiceRelatedType implements org.apache.thrift.TEnum {
  NoType(1),
  Master(2),
  Slave(3);

  private final int value;

  private ServiceRelatedType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceRelatedType findByValue(int value) { 
    switch (value) {
      case 1:
        return NoType;
      case 2:
        return Master;
      case 3:
        return Slave;
      default:
        return null;
    }
  }
}
