/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.soldier.framework.message_bus.swig;

public class IMessageConsumerSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IMessageConsumerSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMessageConsumerSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MessageAgentBridgeJNI.delete_IMessageConsumerSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    MessageAgentBridgeJNI.IMessageConsumerSwig_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    MessageAgentBridgeJNI.IMessageConsumerSwig_change_ownership(this, swigCPtr, true);
  }

  public int onStartUp() {
    return MessageAgentBridgeJNI.IMessageConsumerSwig_onStartUp(swigCPtr, this);
  }

  public int onConsumeMessage(String topic, byte[] data) {
    return MessageAgentBridgeJNI.IMessageConsumerSwig_onConsumeMessage(swigCPtr, this, topic, data);
  }

  protected IMessageConsumerSwig() {
    this(MessageAgentBridgeJNI.new_IMessageConsumerSwig(), true);
    MessageAgentBridgeJNI.IMessageConsumerSwig_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
