/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.route.dao;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RouteType implements org.apache.thrift.TEnum {
  Mod(1),
  RR(2),
  XL(3),
  K8SSrv(4),
  K8SMod(5);

  private final int value;

  private RouteType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RouteType findByValue(int value) { 
    switch (value) {
      case 1:
        return Mod;
      case 2:
        return RR;
      case 3:
        return XL;
      case 4:
        return K8SSrv;
      case 5:
        return K8SMod;
      default:
        return null;
    }
  }
}
