/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.oa.user.ao;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OaUserErrorCode implements org.apache.thrift.TEnum {
  UserNameOrPasswordError(60001),
  UserNameAlreadyExist(60002),
  UserNotExist(60003);

  private final int value;

  private OaUserErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OaUserErrorCode findByValue(int value) { 
    switch (value) {
      case 60001:
        return UserNameOrPasswordError;
      case 60002:
        return UserNameAlreadyExist;
      case 60003:
        return UserNotExist;
      default:
        return null;
    }
  }
}
