apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnas-ssd-0001
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-ssd
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /pv0001
    server: 325434bb41-ukf77.cn-shanghai.nas.aliyuncs.com
    
