apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvzookeeper-datalog
  labels:
    pv.bind: zookeeper-datalog
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /datalog
    server: 3efbe4af91-uax26.cn-shanghai.nas.aliyuncs.com