kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-zookeeper-datalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      pv.bind: zookeeper-datalog