apiVersion: v1
kind: Service
metadata:
  name: zk-client
spec:
  ports:
  - name: zk-client-port
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper
  type: ClusterIP