apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-server-deploy
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        network.out.enabled: 'false'
      containers:
      - name: zookeeper
        image: docker-registry.default.svc:5000/soldier-platform/zookeeper:3.4
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: data
          mountPath: /data
        - name: datalog
          mountPath: /datalog
        env:
        - name: ZOO_STANDALONE_ENABLED
          value: 'true'
        - name: ZOO_AUTOPURGE_PURGEINTERVAL
          value: '12'
        - name: ZOO_MAX_CLIENT_CNXNS
          value: '200'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-zookeeper-data
      - name: datalog
        persistentVolumeClaim:
          claimName: pvc-zookeeper-datalog