/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.soldier.watcher.file.swig;

public class FileWatcherSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileWatcherSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileWatcherSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FileWatcherJNI.delete_FileWatcherSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void init(IFileListener global_listener) {
    FileWatcherJNI.FileWatcherSwig_init(IFileListener.getCPtr(global_listener), global_listener);
  }

  public static void addWatchFile(String file_path) {
    FileWatcherJNI.FileWatcherSwig_addWatchFile(file_path);
  }

  public static void removeWatchFile(String file_path) {
    FileWatcherJNI.FileWatcherSwig_removeWatchFile(file_path);
  }

  public static void initNativeLogger(String log_module) {
    FileWatcherJNI.FileWatcherSwig_initNativeLogger(log_module);
  }

  public static void destroy() {
    FileWatcherJNI.FileWatcherSwig_destroy();
  }

  public FileWatcherSwig() {
    this(FileWatcherJNI.new_FileWatcherSwig(), true);
  }

}
