cc_binary(
    name = 'message_broker',
    srcs = [
        'src/message_broker.cpp',
        'src/main.cpp',
    ],
    deps = [
        '//cpp_platform/message_bus:message_bus_api',
        '#boost_program_options',
    ]
)