apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: message-broker
    
- kind: BuildConfig
  apiVersion: v1
  metadata: 
    name: "message-broker"
    annotations: 
      description: "Defines how to build message-broker"
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    nodeSelector:
      node-role.soldier.platform/builder: 'true'
    source: 
      type: "Git"
      git: 
        uri: "ssh://git@git.soldier-tools.svc:29418/soldier-platform/message_broker.git"
        ref: "master"
      sourceSecret:
        name: xueqiao-git
    strategy: 
      type: Source
      sourceStrategy: 
        incremental: true
        from: 
          kind: ImageStreamTag
          namespace: soldier-platform
          name: cpp-platform:latest
    output:
      to:
        kind: ImageStreamTag
        name: "message-broker:1.0"
    triggers: 
    - type: ImageChange
    - type: ConfigChange
    - type: Generic
      generic: 
        secret: "8ksdfk1sdf8120sdflzsdf1230sdfl1239sdffiwerk1lsdf"