/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.soldier.platform.attr;

public final class ReporterType {
  public final static ReporterType REPORTER_TYPE_MINUTE = new ReporterType("REPORTER_TYPE_MINUTE");
  public final static ReporterType REPORTER_TYPE_THIRTYSECONDS = new ReporterType("REPORTER_TYPE_THIRTYSECONDS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ReporterType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ReporterType.class + " with value " + swigValue);
  }

  private ReporterType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ReporterType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ReporterType(String swigName, ReporterType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ReporterType[] swigValues = { REPORTER_TYPE_MINUTE, REPORTER_TYPE_THIRTYSECONDS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

