apiVersion: v1
kind: Service
metadata:
  name: git-webhook
spec:
  ports:
    - name: git-webhook-port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: git-webhook
  type: ClusterIP