#!/bin/bash

blade_dir=$(cd $(dirname $0) && pwd)
cd $blade_dir

target_dir=$1
if [ $# -lt 1 ];then
    echo "$0 target_dir"
    exit 1
fi


echo -n "Installing vim scripts..."
mkdir -p ~/.vim/{syntax,ftdetect,indent}
ln -sf $blade_dir/vim/ftdetect/* ~/.vim/ftdetect/
ln -sf $blade_dir/vim/syntax/* ~/.vim/syntax/
ln -sf $blade_dir/vim/indent/* ~/.vim/indent/
echo ", Done."

mkdir -p $target_dir
echo -n "Installing blade auxiliary tools..."
ln -sf $blade_dir/{genlibbuild,lsnobuild,lsrc,merge-static-libs,bladefunctions} $target_dir
if [ ! -f ~/.bashrc ] || ! grep "bladefunctions" ~/.bashrc 2>&1 >/dev/null; then
    echo "test -s $target_dir/bladefunctions && . $target_dir/bladefunctions || true" >> ~/.bashrc
fi
echo ", Done."

echo -n "Installing blade..."
ln -sf $blade_dir/blade $target_dir
echo ", Done."

