/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.soldier.platform.web.config.dao;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ConfigType implements org.apache.thrift.TEnum {
  AllConfig(1),
  HttpConfig(2);

  private final int value;

  private ConfigType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ConfigType findByValue(int value) { 
    switch (value) {
      case 1:
        return AllConfig;
      case 2:
        return HttpConfig;
      default:
        return null;
    }
  }
}
