cc_binary(
    name = 'applog_test',
    srcs = [
        'applog_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'net_test',
    srcs = [
        'net_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'gethostbyname_test',
    srcs = [
        'gethostbyname_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'hash_test',
    srcs = [
        'hash_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp',
    ]
)

cc_binary(
    name = 'file_test',
    srcs = [
        'file_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'url_test',
    srcs = [
        'url_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'shm_object_test',
    srcs = [
        'shm_object_test.cpp',
    ], 
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'os_test',
    srcs = [
        'os_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)

cc_binary(
    name = 'string_test',
    srcs = [
        'string_test.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp'
    ]
)