cc_library(
    name='svrcpp',
    srcs = [
        'comm_constants.cpp',
        'comm_types.cpp',
        'protocol_util.cpp',
        'stub_base.cpp',
    ],
    deps = [
        '//cpp_platform/base:soldier_basecpp',
        '//cpp_platform/route:route_agent',
        '//cpp_platform/thirdparty/thrift:thriftnb',
        '//cpp_platform/thirdparty/thrift:thrift',
    ],
    export_incs = [
        '.'
    ]
)